### PR TITLE
Combining epics and normal middleware in readme

### PR DESCRIPTION
**Pull request by Henge9**
[Link to issue related to this pr.](https://github.com/brianegan/dart_redux_epics/issues/12) 
I suggest that the information should be in the docs for easy access. 

Thank you for all the good plugins.

### CODE REVIEW

**Comment by MichaelMarner** [comment]
Travis CI failed due to the restriction on the version of `test` to use. I have updated pubspec in my PR:

https://github.com/brianegan/dart_redux_epics/pull/20

That makes the Travis build pass again

**Comment by Henge9** [comment]
Thank you for fixing the version stuff. How do I restart Travis? Is it needed for a small change in readme?

**Comment by MichaelMarner** [comment]
You should merge master into your fork, which will trigger a new Travis build

**Comment by Henge9** [comment]
Thank you. That worked fine.

**Comment by brianegan** [comment]
Thanks! Appreciate the contribution. Back from vacation, I'll merge this up.

**Pull request merged**
